services:
  postgres:
    image: "postgres:17.8@sha256:1eada89ec2521ae0f61125f6bdaf83bbbf88a43fecda48d112a83bb92df75c36"
    environment:
      POSTGRES_USER: drinks
      POSTGRES_PASSWORD: drinks
      POSTGRES_DB: drinks
    volumes:
      - db:/var/lib/postgresql/data

  drinks:
    build: .
    env_file:
      - drinks.env
    environment:
      POSTGRES_CONNECTION_STRING: postgresql://drinks:drinks@postgres/drinks
      MAIL_USE_STARTTLS: "true"
      SCANNER_DEVICE_PATH: "/dev/ttyBarcode"
      DISPLAY: ":0"
    devices:
      - "/dev/ttyBarcode:/dev/ttyBarcode"
    volumes:
      - /root/.Xauthority:/root/.Xauthority
      - /tmp/.X11-unix:/tmp/.X11-unix

volumes:
  db:
