services:
  postgres:
    image: "postgres:17.9@sha256:681f6b2a528c5ef8c162859b778b7e1e27728c977f587a495f34e28b041901f7"
    environment:
      POSTGRES_USER: drinks
      POSTGRES_PASSWORD: drinks
      POSTGRES_DB: drinks
    volumes:
      - db:/var/lib/postgresql/data

  drinks:
    build: .
    env_file:
      - drinks.env
    environment:
      POSTGRES_CONNECTION_STRING: postgresql://drinks:drinks@postgres/drinks
      MAIL_USE_STARTTLS: "true"
      SCANNER_DEVICE_PATH: "/dev/ttyBarcode"
      DISPLAY: ":0"
    devices:
      - "/dev/ttyBarcode:/dev/ttyBarcode"
    volumes:
      - /root/.Xauthority:/root/.Xauthority
      - /tmp/.X11-unix:/tmp/.X11-unix

volumes:
  db:
