services:
  postgres:
    image: "postgres:17.9@sha256:2cd82735a36356842d5eb1ef80db3ae8f1154172f0f653db48fde079b2a0b7f7"
    environment:
      POSTGRES_USER: drinks
      POSTGRES_PASSWORD: drinks
      POSTGRES_DB: drinks
    volumes:
      - db:/var/lib/postgresql/data

  drinks:
    build: .
    env_file:
      - drinks.env
    environment:
      POSTGRES_CONNECTION_STRING: postgresql://drinks:drinks@postgres/drinks
      MAIL_USE_STARTTLS: "true"
      SCANNER_DEVICE_PATH: "/dev/ttyBarcode"
      DISPLAY: ":0"
    devices:
      - "/dev/ttyBarcode:/dev/ttyBarcode"
    volumes:
      - /root/.Xauthority:/root/.Xauthority
      - /tmp/.X11-unix:/tmp/.X11-unix

volumes:
  db:
