services:
  postgres:
    image: "postgres:17.8@sha256:69dddb030ab69d669d8d7c6abf67aeb448178e5270d5f123a21f4f7ac8b46a24"
    environment:
      POSTGRES_USER: drinks
      POSTGRES_PASSWORD: drinks
      POSTGRES_DB: drinks
    ports:
      - 5432:5432


  keycloak:
    image: "quay.io/keycloak/keycloak:26.5@sha256:ae8efb0d218d8921334b03a2dbee7069a0b868240691c50a3ffc9f42fabba8b4"
    environment:
        KC_BOOTSTRAP_ADMIN_USERNAME: admin
        KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    ports:
        - "8080:8080"
    command: "start-dev --proxy-headers xforwarded --import-realm"
    volumes:
      # Old data isn't compatible since we upgrade from 25.0.7 to 26.2?
      # Commenting out here for simplicity. Feel free to fix
      # - keycloak:/opt/keycloak/data
      # To update the realm, stop keycloak and run:
      # docker compose -f compose.dev.yaml run -it keycloak export --file /opt/keycloak/data/import/flipdot.json --realm flipdot
      # Attention: The file it exports isn't importable.
      # Explanation at https://github.com/flipdot/drinks-touch/pull/213#discussion_r1769129578
      - ./keycloak/realms/:/opt/keycloak/data/import


  mailpit:
    image: axllent/mailpit@sha256:030f06031ce5c60913ac9363da1ab0d4be6fd2a78147dd0e1ca0fcac665d6b34
    restart: always
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: true
      MP_SMTP_AUTH_ALLOW_INSECURE: true
    ports:
      - 8025:8025
      - 1025:1025

volumes:
  keycloak:
