services:
  postgres:
    image: "postgres:16.1"
    environment:
      POSTGRES_USER: drinks
      POSTGRES_PASSWORD: drinks
      POSTGRES_DB: drinks
    ports:
      - 5432:5432

  # user: cn=admin,dc=example,dc=org
  # password: admin
  openldap:
    image: osixia/openldap:1.5.0
    environment:
        LDAP_LOG_LEVEL: "256"
        LDAP_ORGANISATION: "Example Inc."
        LDAP_DOMAIN: "flipdot.org"
        LDAP_BASE_DN: "dc=flipdot,dc=org"
        LDAP_ADMIN_PASSWORD: "admin"
        LDAP_CONFIG_PASSWORD: "config"
        LDAP_READONLY_USER: "false"
        #LDAP_READONLY_USER_USERNAME: "readonly"
        #LDAP_READONLY_USER_PASSWORD: "readonly"
        LDAP_RFC2307BIS_SCHEMA: "false"
        LDAP_BACKEND: "mdb"
        LDAP_TLS: "false"
        LDAP_REPLICATION: "false"
        KEEP_EXISTING_CONFIG: "false"
        LDAP_REMOVE_CONFIG_AFTER_SETUP: "true"
    ports:
        - "389:389"
        - "636:636"
    volumes:
      - ./docker/flipdot.ldif:/root/flipdot.ldif:ro
#    entrypoint: "sleep 3 && service slapd stop && slapadd -n 0 < /root/flipdot.ldif && cat /root/flipdot.ldif && service slapd start"
#    entrypoint: "sleep 3 && service slapd stop && slapadd -n 0 < /root/flipdot.ldif && /container/tool/run"
    entrypoint: "/container/tool/run &; sleep 3 && service slapd stop && slapadd -n 0 < /root/flipdot.ldif && service slapd start && tail -f /var/log/ldap.log"


  hackertool:
    image: osixia/phpldapadmin:latest
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: "openldap"
      PHPLDAPADMIN_HTTPS: "false"
    ports:
      - "9090:80"
    depends_on:
      - openldap

  mailpit:
    image: axllent/mailpit
    restart: always
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: true
      MP_SMTP_AUTH_ALLOW_INSECURE: true
    ports:
      - 8025:8025
      - 1025:1025