services:
  postgres:
    image: "postgres:17.0"
    environment:
      POSTGRES_USER: drinks
      POSTGRES_PASSWORD: drinks
      POSTGRES_DB: drinks
    ports:
      - 5432:5432

  # user: cn=admin,dc=example,dc=org
  # password: admin
  openldap:
    image: osixia/openldap:1.5.0
    environment:
        LDAP_LOG_LEVEL: "256"
        LDAP_ORGANISATION: "Example Inc."
        LDAP_DOMAIN: "flipdot.org"
        LDAP_BASE_DN: "dc=flipdot,dc=org"
        LDAP_ADMIN_PASSWORD: "admin"
        LDAP_CONFIG_PASSWORD: "config"
        LDAP_READONLY_USER: "false"
        #LDAP_READONLY_USER_USERNAME: "readonly"
        #LDAP_READONLY_USER_PASSWORD: "readonly"
        LDAP_RFC2307BIS_SCHEMA: "false"
        LDAP_BACKEND: "mdb"
        LDAP_TLS: "false"
        LDAP_REPLICATION: "false"
        KEEP_EXISTING_CONFIG: "false"
        LDAP_REMOVE_CONFIG_AFTER_SETUP: "false"
        LDAP_SEED_INTERNAL_SCHEMA_PATH: "/assets/openldap/custom/schema/"
        LDAP_SEED_INTERNAL_LDIF_PATH: "/assets/openldap/custom/ldif/"
    ports:
        - "389:389"
        - "636:636"
    volumes:
      - ./docker/flipdot.schema:/assets/openldap/custom/schema/flipdot.schema
      - ./docker/flipdot.ldif:/assets/openldap/custom/ldif/flipdot.ldif

  keycloak:
    image: "quay.io/keycloak/keycloak:25.0.4"
    environment:
        KEYCLOAK_ADMIN: admin
        KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
        - "8080:8080"
    command: "start-dev --proxy-headers xforwarded --import-realm"
    volumes:
      - keycloak:/opt/keycloak/data
      # To update the realm, stop keycloak and run:
      # docker compose -f compose.dev.yaml run -it keycloak export --file /opt/keycloak/data/import/flipdot.json --realm flipdot
      # Attention: The file it exports isn't importable.
      # Explanation at https://github.com/flipdot/drinks-touch/pull/213#discussion_r1769129578
      - ./keycloak/realms/:/opt/keycloak/data/import


  hackertool:
    image: osixia/phpldapadmin:latest
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: "openldap"
      PHPLDAPADMIN_HTTPS: "false"
    ports:
      - "9090:80"
    depends_on:
      - openldap

  mailpit:
    image: axllent/mailpit
    restart: always
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: true
      MP_SMTP_AUTH_ALLOW_INSECURE: true
    ports:
      - 8025:8025
      - 1025:1025

volumes:
  keycloak:
