services:
  postgres:
    image: "postgres:16.1"
    environment:
      POSTGRES_USER: drinks
      POSTGRES_PASSWORD: drinks
      POSTGRES_DB: drinks
    volumes:
      - db:/var/lib/postgresql/data

  drinks:
    build: .
    env_file:
      - drinks.env
    environment:
      POSTGRES_CONNECTION_STRING: postgresql://drinks:drinks@postgres/drinks
      MAIL_USE_STARTTLS: "true"
      SCANNER_DEVICE_PATH: "/dev/ttyBarcode"
    devices:
      - "/dev/ttyBarcode:/dev/ttyBarcode"

volumes:
  db: