version: '3'
services:
  postgres:
    image: "postgres:16.1"
    environment:
      POSTGRES_USER: drinks
      POSTGRES_PASSWORD: drinks
      POSTGRES_DB: drinks
    ports:
      - 5432:5432
  drinks:
    build: .


