[tool.poetry]
name = "drinks-touch"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"
packages = [{include = "drinks_touch"}]

[tool.poetry.dependencies]
python = "^3.5"
flask = "0.10.1"
flask-compress = "1.4.0"
influxdb = "5.0.0"
jinja2 = "3.1.3"
keyboard = "0.9.13"
pygame = "2.5.2"
qrcode = "6.0"
requests = "2.18.4"
sqlalchemy = "1.0.13"
werkzeug = "0.11.9"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
