#!/bin/bash

# get this script's directory and the multiarch Dockerfile (template) path
THIS=$(dirname $(readlink -f "$0"))
MULTIARCH_DOCKERFILE_TEMPLATE_PATH="$THIS/../multiarch.Dockerfile"
MULTIARCH_DOCKERFILE_PATH="${MULTIARCH_DOCKERFILE_TEMPLATE_PATH/multiarch.Dockerfile/build\/Dockerfile}"

# create gitignored build directory
mkdir "$THIS/../build"

# disable git filemode change detection
git config core.filemode false

# register qemu modules
docker run --rm --privileged multiarch/qemu-user-static:register

# load build variable combinations
archs=()
readarray -t archs < "$THIS/archs.csv"

# push individual tags
for arch in "${archs[@]:1}"
do
  # skip empty lines that someone will surely commit one day
  if [ "$arch" == "" ]
  then
    break
  fi

  parts=( ${arch//,/ } )

  ARCH="${parts[0]}"
  HUB_U="${parts[1]}"
  QEMUARCH="${parts[2]}"
  VARIANT="${parts[3]}"

  if [ "${parts[1]}" == "amd64" ] # default architecture
    then
      # remove MULTIARCH line to build the default image
      sed "/__MULTIARCH_/d" "$MULTIARCH_DOCKERFILE_TEMPLATE_PATH" > "$MULTIARCH_DOCKERFILE_PATH"
    else
      # enable MULTIARCH line to build multiarch images
      curl -L "https://github.com/multiarch/qemu-user-static/releases/download/v3.1.0-2/x86_64_qemu-$QEMUARCH-static.tar.gz" \
        | tar xz -C "docker/build/"
      sed "s/__MULTIARCH_//g" "$MULTIARCH_DOCKERFILE_TEMPLATE_PATH" > "$MULTIARCH_DOCKERFILE_PATH"
  fi

  # build it!
  docker build \
    --platform $ARCH \
    --build-arg HUB_U="$HUB_U" \
    --build-arg QEMUARCH="$QEMUARCH" \
    -f "$MULTIARCH_DOCKERFILE_PATH" \
    -t "${IMAGE_NAME/:/:$QEMUARCH-}" \
    "$THIS/../../"
done
