#!/bin/bash

# get this script's directory
THIS=$(dirname $(readlink -f "$0"))

# load build variable combinations
archs=()
readarray -t archs < "$THIS/archs.csv"
all_manifests=()

# push individual architecture tags
for arch in "${archs[@]:1}"
do
  # skip empty lines that someone will surely commit one day
  if [ "$arch" == "" ]
  then
    break
  fi

  parts=( ${arch//,/ } )

  ARCH="${parts[0]}"
  HUB_U="${parts[1]}"
  QEMUARCH="${parts[2]}"
  VARIANT="${parts[3]}"

  image_name_full="${IMAGE_NAME/:/:$QEMUARCH-}"
  all_manifests+=("$image_name_full")
  annotate_parameters=("--os linux --arch $ARCH")

  if [ "$VARIANT" != "" ]
  then
    annotate_parameters+=("--variant $VARIANT")
  fi

  # push manifest for individual architecture tag
  docker push "$image_name_full"
  docker manifest create "$image_name_full" "$image_name_full"
  docker manifest annotate "$image_name_full" "$image_name_full" ${annotate_parameters[@]}

  # update global manifest
  docker manifest create $IMAGE_NAME ${all_manifests[@]} -a
  docker manifest annotate $IMAGE_NAME "$image_name_full" ${annotate_parameters[@]}

  docker manifest push "$image_name_full"
done

# push global manifest
docker manifest push $IMAGE_NAME

