name: Scheduled Release

on:
  schedule:
    - cron:  '0 0 * * 1' # Every Monday at 00:00 AM UTC on the default branch

jobs:
  analyze-tags:
    runs-on: ubuntu-latest
    outputs:
      previous-tag: ${{ steps.previoustag.outputs.tag }}
      timestamp-diff: ${{ steps.diff.outputs.timestamp-diff }}
    steps:
      - uses: actions/checkout@1e204e9a9253d643386038d443f96446fa156a97 # renovate: tag=v2.3.5
        with:
          fetch-depth: 0
      - name: Get previous tag
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@1.0.0"
      - name: Get seconds from previous tag to now
        id: diff
        shell: bash
        env:
          TIMESTAMP_TAG: ${{ steps.previoustag.outputs.timestamp }}
        run: |
          echo "::set-output name=timestamp-diff::$(expr $(printf '%(%s)T') - $TIMESTAMP_TAG)"

  schedule-release:
    runs-on: ubuntu-latest
    needs: analyze-tags
    if: needs.analyze-tags.outputs.timestamp-diff > 604800 # 604800 equal one week.
    steps:
      - uses: actions/checkout@1e204e9a9253d643386038d443f96446fa156a97 # renovate: tag=v2.3.5
        with:
          token: ${{ secrets.GH_TOKEN }}
      - name: Get next minor version
        id: semvers
        uses: "WyriHaximus/github-action-next-semvers@v1.0"
        with:
          version: ${{ needs.analyze-tags.outputs.previous-tag }}
      - name: manifest Version
        uses: deef0000dragon1/json-edit-action/@cb3f7455e89d659879ab7e4a55cbc9b10c36a713 # renovate: tag=v1
        env:
          KEY: scheduleVersion
          VALUE: ${{ steps.semvers.outputs.patch }}
          FILE: package.json
      - uses: stefanzweifel/git-auto-commit-action@abd87b7d94702070bef78dc1d56b6928b8fa9ecc # renovate: tag=v4.12.0
        with:
          commit_message: 'fix(release): schedule release'